CREATE AVAILABILITY GROUP [AG_PROD]
WITH (DB_FAILOVER = ON, CLUSTER_TYPE = WSFC)
FOR DATABASE [YourDB]
REPLICA ON 
    'SQL-01' WITH (ENDPOINT_URL = 'TCP://SQL-01.domain.com:5022', AVAILABILITY_MODE = SYNCHRONOUS_COMMIT, FAILOVER_MODE = AUTOMATIC),
    'SQL-02' WITH (ENDPOINT_URL = 'TCP://SQL-02.domain.com:5022', AVAILABILITY_MODE = SYNCHRONOUS_COMMIT, FAILOVER_MODE = AUTOMATIC),
    'SQL-03' WITH (ENDPOINT_URL = 'TCP://SQL-03.domain.com:5022', AVAILABILITY_MODE = ASYNCHRONOUS_COMMIT, FAILOVER_MODE = MANUAL);