CREATE ENDPOINT [Hadr_endpoint] 
    STATE=STARTED 
    AS TCP (LISTENER_PORT = 5022, LISTENER_IP = ALL) 
    FOR DATA_MIRRORING (
        ROLE = ALL, 
        AUTHENTICATION = WINDOWS NEGOTIATE, 
        ENCRYPTION = REQUIRED ALGORITHM AES
    );